root: true
env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  describe: readonly
  test: readonly
  expect: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  max-len:
    - error
    - 110
  '@typescript-eslint/no-namespace':
    - off
  react/react-in-jsx-scope:
    - off
  '@typescript-eslint/ban-types':
    - off
  '@typescript-eslint/no-non-null-assertion':
    - off
