root: true
env:
  browser: true
  es6: true
  node: true
  commonjs: true
  'jest/globals': true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
plugins:
  - 'prettier'
  - 'jest'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  max-len:
    - error
    - 100
