root: true
env:
  browser: true
  es6: true
  node: true
  commonjs: true
extends:
  - 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - off
  semi:
    - error
    - always
  max-len:
    - error
    - 100
